name = "Wiener"
uuid = "dfa1e9ad-d968-4ef0-b453-22c2cb35d959"
authors = ["Tobias Alfers <tobias@alfers.eu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
