name = "WienerDiffusionModel"
uuid = "dfa1e9ad-d968-4ef0-b453-22c2cb35d959"
authors = ["Tobias Alfers <tobias@alfers.eu> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
